# Generated by Django 4.2.4 on 2023-08-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='building',
            field=models.CharField(blank=True, choices=[('A', 'Building A'), ('B', 'Building B')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
